GET http://localhost:3000

###
GET http://localhost:3000/songs

### FInd song
GET http://localhost:3000/songs/1


### Create song
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXppY29kZXNAZ21haWwuY29tIiwidXNlcklkIjo2LCJpYXQiOjE3NjUzMTM4MTgsImV4cCI6MTc2NTQwMDIxOH0.lFY-Zg4qm3KfibVVvx22OsNpDGA92zW5c6WCHDkDvoU

{   "title":"Mavin's room",
    "artists":[1],
    "duration":"02:50",
    "release_date":"2025-03-18",
    "lyrics":"we can do better"
}


### Update songs
PUT http://localhost:3000/songs/1
Content-Type: application/json

  {
    "lyrics": "Take man like joke like say i no sabi,Layi Wasabi,Joke man nothing wey you sabi, i for like"
  }


### Delete song
DELETE http://localhost:3000/songs/2


### create palylist
POST  http://localhost:3000/playlists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXppY29kZXNAZ21haWwuY29tIiwidXNlcklkIjo2LCJpYXQiOjE3NjI4NjA1MjQsImV4cCI6MTc2Mjk0NjkyNH0.7zqlqqCX4NFU2ECd3R3-KuQPzOCWR0lL_OWIEqen_bk

{
  "name": "life is good",
  "songs":[1],
  "user":900
}

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"first_name": "Deezi",
"last_name": "Codes",
"email": "deezicodes@gmail.com",
"password": "123456"
}
### deezicodes apikey 29a6bbc3-d77f-416f-81bc-8235a73c29c3

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "deezicodes@gmail.com",
"password": "123456"
}

### Create Artist
POST http://localhost:3000/artists
Content-Type: application/json

{
"user": 6
}

### Get Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwidXNlcklkIjo1LCJpYXQiOjE3NjE2MjEzNzEsImV4cCI6MTc2MTcwNzc3MX0.sLgZgR7VuBqObN1z21nTnBKjWdmYOLWnJkDkQxc5yD8

### Get Auth Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer 29a6bbc3-d77f-416f-81bc-8235a73c29c3


### Enable 2FA
POST http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRlZXppY29kZXNAZ21haWwuY29tIiwidXNlcklkIjo2LCJpYXQiOjE3NjI0OTYyNjYsImV4cCI6MTc2MjU4MjY2Nn0.oF-5ZI9VED0xfhXxLbcva-YAAj1xozmrDtt3VCtdl_E

### Disable 2fa
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRyYWtlZ3JhaGFtQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiYXJ0aXN0SWQiOjEsImlhdCI6MTc2MTE4MTk4OSwiZXhwIjoxNzYxMjY4Mzg5fQ.8igfHTG1YmmCnsLtf0R4hU2qCQ2o5am3KnyquJkXimg

### Validate 2FA Token
POST http://localhost:3000/auth/verify-2fa
Content-Type: application/json

{
"userId":"6",
"token": "243441"
}

### Test Env
GET http://localhost:3000/auth/test


### Convert
POST  http://localhost:3000/audio/convert