GET http://localhost:3000

###
GET http://localhost:3000/songs

### FInd song
GET http://localhost:3000/songs/1
### Create song
POST http://localhost:3000/songs
Content-Type: application/json

{   "title":"God's plan",
    "artists":[1,2],
    "duration":"02:50",
    "release_date":"2025-03-18",
    "lyrics":"And, they wishin' and wishin' and wishin' and wishin' They wishin' on me, yeah"
}


### Update songs
PUT http://localhost:3000/songs/1
Content-Type: application/json

  {
    "lyrics": "Take man like joke like say i no sabi,Layi Wasabi,Joke man nothing wey you sabi, i for like"
  }


### Delete song
DELETE http://localhost:3000/songs/2


### create palylist
POST  http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "life is good",
  "songs":[3],
  "user":3
}

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"first_name": "john",
"last_name": "doe",
"email": "john@gmail.com",
"password": "123456"
}


### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "john@gmail.com",
"password": "123456"
}